use_frameworks!

target 'TNInfoBubble_Example' do
  pod 'TNInfoBubble', :path => '../'

  target 'TNInfoBubble_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
